### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by dimqua** [Nepochal/redshift-tray#6]
I noticed that redshift-tray is relatively RAM-hungly, compared to at least [RedshiftGUI](http://maoserr.com/projects/redshiftgui/) (deprecated) which I used before.

![](http://i.imgur.com/nPXbfmJ.png)

Is it normal, or it should be (can be) fixed?

**Comment by Nepochal** [comment]
Most of the memory is used by the .net framework. It would be possible to reduce the usage by a minimum amount. But it would not worth the efford.
