### ISSUE TITLE
Windows x64 builds

### ISSUE THREAD

**Issue by dimqua** [Nepochal/redshift-tray#8]
Currently, there's no cense to support 32-bit Windows since redshift itself is only available for Windows x64. 

Do you plan to provide 64-bit builds any time soon?

**Comment by manuc66** [comment]
`redshift` have now [32-bit support for windows on dev branch](https://github.com/jonls/redshift#user-content-latest-builds-from-master-branch)

**Comment by Nepochal** [comment]
There are no benefits in using a 64-bit build, but it would use much more memory. So it would make no sense to publish a 64-bit version.
But if you can give me an advantage I will publish one.
