### ISSUE TITLE
High GPU frequency

### ISSUE THREAD

**Issue by loathingKernel** [Nepochal/redshift-tray#9]
Running Redshift Tray causes the GPU to run at the highest frequency even though it doesn't visibly increase the usage of the GPU. I believe it is due to the use of WPF as it is something that I have encountered with other WPF applications too. This behavior manifests after something as simple as hovering the tray icon or opening the menu. In my opinion, this wouldn't be an issue for some regular application, but for something that is supposed to sit in the background and just do its job, it is.

**Comment by Nepochal** [comment]
Yes, WPF uses GPU based hardware accelerated rendering like many other graphical frameworks and Windows itself.
I tested the GPU usage and frequency on three different hardware setups using "MSI Afterburner". I wasn't able to observe a noticeable change in frequency.
Which hardware do you use and which tools did you use to measure the GPU usage? Do you have the same problems on other systems?

**Comment by loathingKernel** [comment]
Yes, this isn't by any means an issue with Redshift Tray itself but rather something similar to a feature request, it would be nice to have a work-around. I have only one system to test it on, which has an Nvidia 560Ti and I got the frequency readings from OpenHardwareMonitor.  Would it be possible to change the rendering backend to a software one in WPF, or use an earlier .Net version? For example OpenHardwareMonitor, which is a .Net 2 application doesn't exhibit the same behaviour.

**Comment by Nepochal** [comment]
OpenHardwareMonitor uses "Windows Forms" instead of WPF. This has nothing to do with .Net 2.
However it seems that it is possible to enforce software rendering in WPF. Could you please replace your Redshift Tray executable with the attached one and check if it solves your GPU problems?

[redshift-tray-swrender.zip](https://github.com/Nepochal/redshift-tray/files/1320248/redshift-tray-swrender.zip)

**Comment by loathingKernel** [comment]
That seems to do the trick just fine. Thank you.

**Comment by Nepochal** [comment]
Good to hear that I was able to help you.
I added a start parameter "/swrender" that you can use in all future versions to enforce software rendering.
